### ISSUE TITLE
Null pointer exception with 0.2.0

### ISSUE THREAD

**Issue by hkroger** [qvantel/sbt-mobilizer#7]
What could be the problem?

```
java.lang.NullPointerException
	at fi.onesto.sbt.mobilizer.PasswordPrompt.reqPassword(PasswordPrompt.scala:13)
	at net.schmizz.sshj.userauth.method.AuthPassword.buildReq(AuthPassword.java:63)
	at net.schmizz.sshj.userauth.method.AbstractAuthMethod.request(AbstractAuthMethod.java:68)
	at net.schmizz.sshj.userauth.UserAuthImpl.authenticate(UserAuthImpl.java:70)
	at net.schmizz.sshj.SSHClient.auth(SSHClient.java:219)
	at fi.onesto.sbt.mobilizer.Deployer$$anonfun$fi$onesto$sbt$mobilizer$Deployer$$connect$1.apply(Deployer.scala:314)
	at fi.onesto.sbt.mobilizer.Deployer$$anonfun$fi$onesto$sbt$mobilizer$Deployer$$connect$1.apply(Deployer.scala:311)
	at fi.onesto.sbt.mobilizer.util$Tap$.tap$extension(util.scala:15)
	at fi.onesto.sbt.mobilizer.Deployer$.fi$onesto$sbt$mobilizer$Deployer$$connect(Deployer.scala:311)
	at fi.onesto.sbt.mobilizer.Deployer$$anonfun$5$$anonfun$apply$35.apply(Deployer.scala:328)
	at fi.onesto.sbt.mobilizer.Deployer$$anonfun$5$$anonfun$apply$35.apply(Deployer.scala:328)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] (*:deploy) java.lang.NullPointerException
[error] Total time: 2 s, completed Feb 19, 2019 12:10:45 AM
```

**Comment by liff** [comment]
Looking at the [relevant line](https://github.com/qvantel/sbt-mobilizer/blob/master/src/main/scala/fi/onesto/sbt/mobilizer/PasswordPrompt.scala#L13) it could be [`System.console()`](https://docs.oracle.com/javase/8/docs/api/java/lang/System.html#console--) or the `client` field. [`Console.readPassword()`](https://docs.oracle.com/javase/8/docs/api/java/io/Console.html#readPassword-java.lang.String-java.lang.Object...-) can also return `null` on EOF but the [`tap`](https://github.com/qvantel/sbt-mobilizer/blob/master/src/main/scala/fi/onesto/sbt/mobilizer/util.scala#L15) call shouldn’t really care since it doesn’t dereference it.

Any chance of running in a debugger to figure out which one it is? I suspect it’s `System.console()` if you are running in some non-interactive setting.
